name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      matrix:
        include:
          - name: Windows
            os: windows-latest
          - name: MacOS
            os: macos-latest
          - name: Linux
            os: ubuntu-20.04
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip' # Cache all pip dependency downloads
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_full.txt
      - name: Install any missing Qt dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y qtbase5-dev libxcb-cursor0 libxcb-xinerama0
          sudo apt update
          sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev mesa-common-dev libicu-dev
      - name: Test with pytest
        run: |
          pip install pytest pytest-cov
          pytest test --cov=gcft_ui --cov=gclib --cov-report=html
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: gcft-htmlcov-${{ matrix.os }}
          path: htmlcov
