name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      matrix:
        include:
          - name: Windows
            os: windows-latest
          - name: MacOS
            os: macos-latest
          - name: Linux
            os: ubuntu-20.04
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_full.txt
    - name: Test with pytest
      run: |
        pip install pytest pytest-cov
        pytest test --cov=gcft_ui --cov=gclib --cov-report=html
    - name: Upload Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: gcft-htmlcov-${{ matrix.os }}
        path: htmlcov
